<Project>
  <Import Project="$(MSBuildThisFileDirectory)Directory.Build.targets.bak" Condition="Exists('$(MSBuildThisFileDirectory)Directory.Build.targets.bak')" />
  <PropertyGroup>
    <RepoRoot>$(MSBuildThisFileDirectory.TrimEnd('\'))</RepoRoot>
    <RepoBuildToolsDir>$(RepoRoot)\build-tools</RepoBuildToolsDir>
    <RepoGenDll>$(RepoBuildToolsDir)\bin\Release\netstandard2.0\BuildInfo.Analyzers.v868.dll</RepoGenDll>
    <RepoGenState>$(RepoBuildToolsDir)\bin\Release\netstandard2.0\BuildInfo.Analyzers.v868.dat</RepoGenState>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(RepoBuildToolsDir)\**\*</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="$(RepoBuildToolsDir)\**\*.cs" />
    <CompilerVisibleProperty Include="SolutionPath" />
    <CompilerVisibleProperty Include="RepoGenState" />
    <Analyzer Include="$(RepoGenDll)" Condition="'$(MSBuildProjectExtension)' == '.csproj' And Exists('$(RepoGenDll)')" />
  </ItemGroup>
</Project>
